### ISSUE TITLE
Warning while using the Speech-to-Text hook - "AudioContext created on page load"

### ISSUE THREAD

**Issue by nitinsaroha** [Riley-Brown/react-speech-to-text#1]
According to autoplay policy changes, I get the warning below. 
`The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.`

https://github.com/Riley-Brown/react-speech-to-text/blob/ad049c982534cee8c2120df830cbfeafe7fff0ef/src/Hooks/useSpeechToText.tsx#L12

More details about the policy - https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio

**Comment by Riley-Brown** [comment]
Thanks for raising this issue. I just refactored a lot of the hook logic last week and this fix was added. Try out the latest code and let me know if you are still running into any issues
