### ISSUE TITLE
Not supported with react latest version 17.0.2

### ISSUE THREAD

**Issue by abhi8233** [Riley-Brown/react-speech-to-text#13]
I am trying to use latest version of this library 0.7.0 with react latest version 17.0.2 but it is not supported with it. It is supported with 16.8.0 only. Can you please let me know if there any solution for this.
![image](https://user-images.githubusercontent.com/69311628/129520727-d2f44115-04cb-4719-b3fa-545e501b6728.png)

**Comment by Riley-Brown** [comment]
Is this still happening for you? Im am not able to reproduce locally using react 17.0.2. I can change the `peerDependencies` to be 
```
"react": ">=16.8.0",
"react-dom": ">=16.8.0"
```
instead which should work with any version of react that is at least 16.8.0 and above as 16.8.0 is needed for hooks API

**Comment by Riley-Brown** [comment]
Just put out an update v0.8.0 with the peerDependencies changes, let me know if that resolves the issue you were facing
