### ISSUE TITLE
Not save audio in my s3 bucket

### ISSUE THREAD

**Issue by Techguybi** [Riley-Brown/react-speech-to-text#18]
I have used that API in my React Applications but in some questions Audio and speech to text not save in my S3 bucket.
I am using free version of that API,
Is there any solution why I am getting that issue?
Thanks in Advance

**Comment by Riley-Brown** [comment]
@Techguybi Are you using google cloud for the speech to text or the built-in browser Web Speech API? You cannot get the speech audio when using the browser Web Speech API
