### ISSUE TITLE
Expose Google Cloud Speech-to-text config

### ISSUE THREAD

**Issue by iwgx** [Riley-Brown/react-speech-to-text#2]
Hi! Great library, really appreciate your work. 

I want to create an app that's not based on US, so I need a way to configure the GCP config especially the language.
I think It's also good consideration if we expose another config so it will be customizable. What do you think?

I'm available if you would like for me to do pull request for this one.

Thank you.

**Comment by Riley-Brown** [comment]
This is a good idea, the google config can be found in the Hooks/index.tsx file on line 215, we can add an optional `googleConfig` param to the hook in order to overwrite the default values
ex: 
```
  const config = {
        encoding: 'LINEAR16',
        languageCode: 'en-US',
        sampleRateHertz: sampleRate,
        ...googleConfig
      };
```

**Comment by Riley-Brown** [comment]
These are the types for the google config, I can create the PR for this or if you want to feel free as well https://cloud.google.com/speech-to-text/docs/reference/rest/v1p1beta1/RecognitionConfig

**Comment by Riley-Brown** [comment]
Just pushed version 0.4.0 with support for a custom `googleCloudRecognitionConfig` and `speechRecognitionProperties` params, added both to readme https://github.com/Riley-Brown/react-speech-to-text#googlecloudrecognitionconfig

Let me know if you run into any issues with new changes

**Comment by Techguybi** [comment]
I have used that API in my React Applications but in some questions Audio and speech to text not save in my S3 bucket. 
I am using free version of that API, 
Is there any solution why I am getting that issue?
Thanks in Advance
