### ISSUE TITLE
Intercept results and pass them to state

### ISSUE THREAD

**Issue by dgastudio** [Riley-Brown/react-speech-to-text#20]
Hey!

First of all, thanks for this wonderful module.

I have a short question. Is it possible to somehow intercept the change in the results and pass them to my custom useState?

I need this to pass the speech results to a textbox

**Comment by Riley-Brown** [comment]
@dgastudio Hi, I'm not sure what you mean by intercept the change in the result. Can you post a codesandbox example of what you're trying to do?

You could use the results array in a useEffect to get the last result and set that to your own state if I understand correctly
```jsx
useEffect(() => {
  const lastResult = results[results.length - 1]
  setMyCustomState(lastResult)
}, [results])
```
