### ISSUE TITLE
Use text-to-speech

### ISSUE THREAD

**Issue by naonvl** [Riley-Brown/react-speech-to-text#21]
Hi i'm new to react, i have a question can i use this module with text-to-speech? i'm trying to create an app that convert user voice to AI generated voice using google Speech API. Thanks

**Comment by Riley-Brown** [comment]
Hi @naonvl, yes you could use this in combination with the SpeechSynthesis API https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis

You could use the latest result from the results array to pass to the speech synthesis API to playback your users speech

```jsx
  const handleTextToSpeech = (text) => {
    const utterance = new SpeechSynthesisUtterance(text);
    speechSynthesis.speak(utterance);
  };

  useEffect(() => {
    if (results.length) {
      const latestResult = results[results.length - 1];
      handleTextToSpeech(latestResult.transcript);
    }
  }, [results]);
```
