### ISSUE TITLE
TS Error: Cannot find name 'SpeechGrammarList'

### ISSUE THREAD

**Issue by jiahao-c** [Riley-Brown/react-speech-to-text#23]
In `/src/Hooks/index.tsx` , `SpeechGrammarList` is used but not defined. Causing the following error:

```
error TS2304: Cannot find name 'SpeechGrammarList'.
```

UPDATE:
Oh wait, `SpeechGrammarList` is part of the Web Speech API. Maybe it's a problem with TypeScript. Will feedback once solve it.

**Comment by Thejava-monk** [comment]
Please share a solution.

**Comment by Becold** [comment]
I've fixed it in my project by adding @types/webspeechapi package to devDependencies.
`npm install @types/webspeechapi --save-dev`

There is probably a better solution today but I can not find it.
