### ISSUE TITLE
How to change  SpeechRecognition lang

### ISSUE THREAD

**Issue by dgastudio** [Riley-Brown/react-speech-to-text#24]
Hey
I have chrome in English, but I would like to define Spanish as well.

it's possible to change the language in cross-browser mode, but not in "native"

any advice? thanks

**Comment by Riley-Brown** [comment]
You could pass the `googleCloudRecognitionConfig` arg to the hook to specify the language code for cross-browser mode
```
 googleCloudRecognitionConfig: {
    languageCode: 'en-US'
  }
```

This language code will only apply for the browsers that don't support the native browser speech API


Read more here https://github.com/Riley-Brown/react-speech-to-text#googlecloudrecognitionconfig

**Comment by dgastudio** [comment]
Hello Riley!

Thank you for your response! But, i don't want to use google cloud. Instead, i want to set language in native mode
as i can see, it's possible, https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/lang

how to apply this functionality in your plugin?

**Comment by Riley-Brown** [comment]
@dgastudio Yes it is also possible to specify the language for native chrome recognition with the `speechRecognitionProperties`

```js
  speechRecognitionProperties: {
    lang: 'es',
  }
```

However, I would not recommend hardcoding a value here as the MDN docs state 
> If not specified, this defaults to the HTML lang attribute value, or the user agent's language setting

So this setting should be automatically set based on the user's browser language settings

**Comment by dgastudio** [comment]
awesome, thank you!
<img width="337" alt="Logbook | HKeeper 🔊 2021-12-04 22-32-19" src="https://user-images.githubusercontent.com/161524/144722282-f0ff1840-32a6-43ad-ae7c-97483b89b9c0.png">
