### ISSUE TITLE
Cross-browser seems not work as expected

### ISSUE THREAD

**Issue by iwgx** [Riley-Brown/react-speech-to-text#4]
If we enable `crossBrowser` and provide `googleApiKey` seems it's still not using Google Cloud for the transcription, so:
- we can see it through network tab that there is no request happened. Which is supposed to happen
- if we change `googleCloudRecognitionConfig` there is nothing changed

Reproduction (I'm just using example code): https://codesandbox.io/s/nifty-raman-thfsj?file=/src/App.js

**Comment by Riley-Brown** [comment]
@iwgx Are you testing on chrome? If so, chrome will still use the speech recognition API since it's available, the cross-browser is intended for other browsers such as Firefox, Edge, Brave, etc.

**Comment by Riley-Brown** [comment]
I also added a `speechRecognitionProperties` param you can pass to the hook the customize the settings for chrome speech recognition API such as language code https://github.com/Riley-Brown/react-speech-to-text#speechrecognitionproperties

**Comment by iwgx** [comment]
I see, thanks for the confirmation

Previously I think if we pass the `crossBrowser` params, it will override the `SpeechRecognition` so It will use GCP in all browser. 
Since I think GCP will more reliable

**Comment by Riley-Brown** [comment]
The reasoning for this is because Chrome is the most popular browser so more users would use the built-in Chrome speech recognition API which is free and provides faster speech-to-text than using the GCP method. 

I can add a `useOnlyGoogleCloud` param to override this if you think it's needed

**Comment by iwgx** [comment]
I thinks that's needed, since we can control if we want:
- only use GCP
- only use Speech Recognition (and handle error in unsupported browser)
- use Speech Recognition with GCP as fallback

BTW the reliability that I mean is in terms of transcription.
I think since GCP process it in their server, it will have higher accuracy than processed the browser

**Comment by iwgx** [comment]
Thanks for the update

And I just learn about that, will investigate further if there is different between them
