### ISSUE TITLE
How to get the Audio file that is used for conversion from speech to text.

### ISSUE THREAD

**Issue by Nitesh-BB** [Riley-Brown/react-speech-to-text#5]
Hi ,

I just want to know if I can get the audio file (blob) that is used for conversion from speech to text ?

thanks in advance.

**Comment by Riley-Brown** [comment]
Hi @Nitesh-BB , sorry for the late response. 

I could return the base64 audio data for each speech result, but only when using the google cloud speech to text flow, I would have to adjust the API a bit to optionally support this. 

Chrome's SpeechRecognition API would not be able to as the speech data is abstracted away

**Comment by Riley-Brown** [comment]
In version 0.7.0 I adjusted the results array to return an array of objects with one of the properties being the recorded speech blob
```
type ResultType = {
  speechBlob?: Blob;
  timestamp: number;
  transcript: string;
};
```

This speech blob will only be returned when using google cloud speech to text as Chrome's SpeechRecogition API does not give access to the recorded speech data. You can opt into the new results by passing `useLegacyResults: false` to the hook

You can use the new `speechBlob` property to create a playable audio file using object url 
```
<audio src={window.URL.createObjectUrl(speechBlob)} controls={true} />
```

Or read the blob as base64 using FileReader

```
const reader = new FileReader()
reader.readAsDataURL(speechBlob)

reader.onloadend = () => {
    // do something here with reader.result
  }
```

**Comment by Techguybi** [comment]
Hi,
To get the recorded audio in chrome only , for that do I need to create API key in the googlecloud?
How can I get audio in the app.js file? is there any full script for that?

Thanks

**Comment by Riley-Brown** [comment]
> Hi, To get the recorded audio in chrome only , for that do I need to create API key in the googlecloud? How can I get audio in the app.js file? is there any full script for that?
> 
> Thanks

@Techguybi Currently, the only way to get the recorded audio is by setting `useOnlyGoogleCloud: true` in the hook config, this will require a valid google cloud speech api key

```jsx
  const {
    error,
    isRecording,
    results,
    startSpeechToText,
    stopSpeechToText,
  } = useSpeechToText({
    googleApiKey: process.env.REACT_APP_API_KEY,
    useLegacyResults: false
    useOnlyGoogleCloud: true
  });

results.map(result => {
  // result will contain the recorded microphone data
  const url = window.URL.createObjectURL(result.speechBlob)
})
```
